from advisor.resume.domain.constants import (
    MAX_BULLETS_PER_ROLE,
    MAX_ROLES,
    MAX_SKILLS,
    MAX_TEXT,
    PARTIAL_WITHIN,
)
from advisor.resume.domain.content import (
    Bullet,
    Coverage,
    Options,
    Origin,
    Position,
    ResumeContent,
    ResumeError,
    Template,
    Verdict,
    VersionSource,
    assert_well_formed,
    assert_written_lines_cited,
    coverage,
    mark_edits,
    settle_revision,
)
from advisor.resume.domain.events import ResumeEvent, ResumeTailored, ResumeVersionSaved
from advisor.resume.domain.export import Export, ExportStatus
from advisor.resume.domain.repositories import (
    ExportFilter,
    ExportRepository,
    OwnerResumes,
    Repository,
    ResumeUnitOfWork,
    ResumeVersionFilter,
    ResumeVersionRepository,
    RevisionFilter,
    RevisionRepository,
    TailoredResumeFilter,
    TailoredResumeRepository,
)
from advisor.resume.domain.revision import Revision
from advisor.resume.domain.tailored_resume import ResumeStatus, ResumeVersion, TailoredResume

__all__ = [
    "MAX_BULLETS_PER_ROLE",
    "MAX_ROLES",
    "MAX_SKILLS",
    "MAX_TEXT",
    "PARTIAL_WITHIN",
    "Bullet",
    "Coverage",
    "Export",
    "ExportFilter",
    "ExportRepository",
    "ExportStatus",
    "Options",
    "Origin",
    "OwnerResumes",
    "Position",
    "Repository",
    "ResumeContent",
    "ResumeError",
    "ResumeEvent",
    "ResumeStatus",
    "ResumeTailored",
    "ResumeUnitOfWork",
    "ResumeVersion",
    "ResumeVersionFilter",
    "ResumeVersionRepository",
    "ResumeVersionSaved",
    "Revision",
    "RevisionFilter",
    "RevisionRepository",
    "TailoredResume",
    "TailoredResumeFilter",
    "TailoredResumeRepository",
    "Template",
    "Verdict",
    "VersionSource",
    "assert_well_formed",
    "assert_written_lines_cited",
    "coverage",
    "mark_edits",
    "settle_revision",
]
