"""Assessment's entities: this user's dimensions, the assessments and scores
taken against them, follow-up questions and the rounds that raise them, and
fits against roles and postings.

Assessments, scores and fits are immutable snapshots: each records the profile
version, model and template it came from, so a stale one can be detected
(domain section 2.4). ``advisor.assessment.infra`` maps these to and from the
database.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime
from enum import StrEnum
from typing import Any

from advisor.assessment.domain.dimensions import LineageKind


@dataclass(slots=True)
class SkillDimension:
    """One axis of *this user's* skills; there is no global taxonomy.

    ``key`` is reused across re-assessments, which is what lets two
    assessments be compared to show progress.
    """

    id: uuid.UUID
    owner_id: uuid.UUID
    key: str
    name: str
    short_name: str
    retired_at: datetime | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

    def rename(self, *, name: str, short_name: str) -> None:
        """Seen again: take the latest name, and it is live again."""
        self.name = name
        self.short_name = short_name
        self.retired_at = None

    def retire(self, at: datetime) -> None:
        self.retired_at = at


@dataclass(slots=True)
class SkillAssessment:
    id: uuid.UUID
    owner_id: uuid.UUID
    profile_version: int
    model_id: str
    template_version: str
    created_at: datetime | None = None


@dataclass(slots=True)
class AssessedScore:
    """One dimension's score within one assessment."""

    id: uuid.UUID
    owner_id: uuid.UUID
    assessment_id: uuid.UUID
    dimension_key: str
    score: int
    confidence: float
    read: str
    evidence_ids: tuple[str, ...]


@dataclass(slots=True)
class DimensionChange:
    """A dimension added, renamed or merged away, so radar history lines up."""

    id: uuid.UUID
    owner_id: uuid.UUID
    assessment_id: uuid.UUID
    kind: LineageKind
    dimension_key: str
    from_keys: tuple[str, ...] = ()
    previous_name: str | None = None
    recorded_at: datetime | None = None


@dataclass(slots=True)
class FollowUpQuestion:
    """Raised when a dimension's confidence is below the threshold."""

    id: uuid.UUID
    owner_id: uuid.UUID
    assessment_id: uuid.UUID
    dimension_key: str
    text: str
    why: str
    options: tuple[str, ...]
    answer: str | None = None
    answered_at: datetime | None = None
    # Set when a newer round replaced it before it was answered.
    retired_at: datetime | None = None
    created_at: datetime | None = None

    def answered(self, answer: str, *, at: datetime) -> None:
        self.answer = answer
        self.answered_at = at

    def retire(self, at: datetime) -> None:
        self.retired_at = at


class QuestionRoundStatus(StrEnum):
    """A round is generated by a background job, so it exists before it is
    ready, and the page polls it (ADR 0006).

    ``superseded`` means a newer round was requested before this one finished;
    its job stops without calling the model, or discards what the model said.
    """

    GENERATING = "generating"
    READY = "ready"
    FAILED = "failed"
    SUPERSEDED = "superseded"


class QuestionRoundTrigger(StrEnum):
    """Why a round was requested (ADR 0012)."""

    # A sync, a résumé upload or a disconnect changed the evidence.
    EVIDENCE = "evidence"
    # An analysis finished, including the one an answer starts.
    ASSESSMENT = "assessment"


@dataclass(slots=True)
class QuestionRound:
    """One generation of follow-up questions for one assessment's thin
    dimensions. The newest ready round's questions are the open ones."""

    id: uuid.UUID
    owner_id: uuid.UUID
    assessment_id: uuid.UUID
    trigger: QuestionRoundTrigger
    status: QuestionRoundStatus
    created_at: datetime
    question_count: int = 0
    error_code: str | None = None
    error_message: str | None = None
    finished_at: datetime | None = None

    @classmethod
    def requested(
        cls,
        *,
        owner_id: uuid.UUID,
        assessment_id: uuid.UUID,
        trigger: QuestionRoundTrigger,
        at: datetime,
    ) -> QuestionRound:
        return cls(
            id=uuid.uuid4(),
            owner_id=owner_id,
            assessment_id=assessment_id,
            trigger=trigger,
            status=QuestionRoundStatus.GENERATING,
            created_at=at,
        )

    @property
    def is_generating(self) -> bool:
        return self.status is QuestionRoundStatus.GENERATING

    def ready(self, *, count: int, at: datetime) -> None:
        self.status = QuestionRoundStatus.READY
        self.question_count = count
        self.finished_at = at

    def failed(self, *, code: str, message: str, at: datetime) -> None:
        self.status = QuestionRoundStatus.FAILED
        self.error_code = code
        self.error_message = message
        self.finished_at = at

    def superseded(self, at: datetime) -> None:
        self.status = QuestionRoundStatus.SUPERSEDED
        self.finished_at = at


class AnalysisRunStatus(StrEnum):
    """An analysis runs in the background, so it is recorded before it starts
    and the page polls it (ADR 0006, ADR 0018)."""

    RUNNING = "running"
    READY = "ready"
    FAILED = "failed"


@dataclass(slots=True)
class AnalysisRun:
    """One request to analyse this user's evidence. The assessment it writes
    is a separate snapshot; this only says whether it is still being made, and
    why it could not be."""

    id: uuid.UUID
    owner_id: uuid.UUID
    status: AnalysisRunStatus
    started_at: datetime
    finished_at: datetime | None = None
    error_code: str | None = None
    error_message: str | None = None

    @classmethod
    def requested(cls, *, owner_id: uuid.UUID, at: datetime) -> AnalysisRun:
        return cls(
            id=uuid.uuid4(), owner_id=owner_id, status=AnalysisRunStatus.RUNNING, started_at=at
        )

    @property
    def is_running(self) -> bool:
        return self.status is AnalysisRunStatus.RUNNING

    def ready(self, at: datetime) -> None:
        self.status = AnalysisRunStatus.READY
        self.finished_at = at

    def failed(self, *, code: str, message: str, at: datetime) -> None:
        self.status = AnalysisRunStatus.FAILED
        self.error_code = code
        self.error_message = message
        self.finished_at = at


@dataclass(slots=True)
class RoleFit:
    """Fit between this user and one role or one pasted posting.

    Fit lives on the User x Role pair, never on the role. Exactly one of
    ``role_id`` and ``private_posting_id`` is set.
    """

    id: uuid.UUID
    owner_id: uuid.UUID
    assessment_id: uuid.UUID
    role_id: uuid.UUID | None
    private_posting_id: uuid.UUID | None
    score: int
    reasoning: str
    target_profile: dict[str, int]
    gaps: tuple[dict[str, Any], ...]
    uncovered: tuple[dict[str, Any], ...]
    model_id: str
    template_version: str
    requirements: tuple[dict[str, Any], ...] = ()
    requirement_map: dict[str, str | None] = field(default_factory=dict)
    created_at: datetime | None = None

    def __post_init__(self) -> None:
        if (self.role_id is None) == (self.private_posting_id is None):
            raise ValueError("a fit is for exactly one role or one posting")

    @property
    def target(self) -> uuid.UUID:
        """What the fit is against: the role, or the pasted posting."""
        target = self.role_id or self.private_posting_id
        assert target is not None
        return target
